<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Thu Aug 02 2018 15:13:48 GMT+0000 (UTC)). */
return array(
	'public/dist/rml_shortcode.js' => '8bba56b7ae3b840558d260ceadd88a6c',
	'public/dist/rml.js' => 'a5c8245f730e6ffd65f6e5b0a068943f',
	'public/dist/rml.css' => '744bfc5bb90f330d159211a7dd276f26',
	'public/dev/rml_shortcode.js' => 'fdc7b0f805426e0bcea294273ce1c271',
	'public/dev/rml.js' => '6d4d15f247e341eb65859b4d534e73f1',
	'public/dev/rml_shortcode.css' => '9a7cac4970a885476f97fd937b689eff',
	'public/dev/rml.css' => '9dd61d7f5e4ddb6703060047a7ffecaa',
);
